printWidth: 120
tabWidth: 2
useTabs: false
 proseWrap: never
  quoteProps: as-needed
  requirePragma: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
 jsxSingleQuote: false
arrowParens: avoid
proseWrap: always
 htmlWhitespaceSensitivity: ignore
  insertPragma: false

  vueIndentScriptAndStyle: false
  singleAttributePerLine: false